[agent]
system_instruction_name = "rag_agent"
tool_names = ["local_search"]
  [agent.generation_config]
      provider = "litellm"
      model = "qwen25b70"
      concurrent_request_limit = 32
      api_base = 'http://10.1.150.105:9997/v1' 
      rerank_model="jina-reranker-v2"
      rerank_url='http://10.1.150.106:9997/v1/rerank'   

[completion]
provider = "litellm"
concurrent_request_limit = 32
  [completion.generation_config]    
    model = "qwen25b70"    
    api_base = 'http://10.1.150.105:9997/v1'

[embedding]
  provider = "litellm"
  #base_model = "xinference/bce-embedding-base_v1" # defaults to `text-embedding-3-large`
  #base_dimension = 768 # defaults to `3072`
  base_model = "xinference/bge-small-zh" # defaults to `text-embedding-3-large`
  base_dimension = 512 # defaults to `3072`
  base_url = 'http://10.1.150.106:9997/v1'
  batch_size = 128
  add_title_as_prefix = true

[database]
provider = "postgres"
  #user = "user"
  #password = "password"
  #host = '0.0.0.0'
  #port = "5432"
  #db_name = 'r2r_jq'
  your_project_name = "r2r_new_project"
  [database.graph_creation_settings]
    clustering_mode = "remote"
    graph_entity_description_prompt = "graphrag_entity_description"
    entity_types = [] # if empty, all entities are extracted
    relation_types = [] # if empty, all relations are extracted
    fragment_merge_count = 4 # number of fragments to merge into a single extraction
    max_knowledge_relationships = 100
    max_description_input_length = 20000
    generation_config = {provider = "litellm", model = "qwen25b70",api_base = 'http://10.1.150.105:9997/v1'}
  
  [database.graph_entity_deduplication_settings]
    graph_entity_deduplication_type = "by_name"
    graph_entity_deduplication_prompt = "graphrag_entity_deduplication"
    max_description_input_length = 20000
    generation_config = {provider = "litellm", model = "qwen25b70",api_base = 'http://10.1.150.105:9997/v1'}

  [database.graph_enrichment_settings]
    community_reports_prompt = "graphrag_community_reports"
    max_summary_input_length = 20000
    leiden_params = {}
    generation_config = {provider = "litellm", model = "qwen25b70",api_base = 'http://10.1.150.105:9997/v1'}
  
  [database.graph_search_settings]
    generation_config = {provider = "litellm", model = "qwen25b70",api_base = 'http://10.1.150.105:9997/v1'}

[ingestion]
provider = "r2r"
chunking_strategy = "recursive"
chunk_size = 500
chunk_overlap = 100
chunks_for_document_summary = 4
document_summary_model = "qwen25b70"
    [ingestion.extra_parsers]
    pdf = "zerox"

[orchestration]
provider = "hatchet"
kg_creation_concurrency_limit = 32
ingestion_concurrency_limit = 16
kg_concurrency_limit = 8
